import {loginRequest, logoutRequest, updateUserRequest} from './auth';

import {
  getAcculaLabTests,
  getCueLabTests,
  // getMolecularLabTests,
  getPendingLabTest,
  getRapidAntigenTests,
  updateSelectedSite,
  deleteTest,
  updateTestConfig,
  updateCreateSource,
  updateTestType,
  sendTestToLab,
  updateTestLabType,
  updateTestEmpInfo,
} from './tests';

import {
  updatePrinter,
  updateEventData,
  updateClients,
  updateSites,
  updateLabs,
  updateTestSettings,
  printerRequest,
  printerRequestSuccess,
  printerRequestFailure,
} from './eventConfig';

export {
  loginRequest,
  logoutRequest,
  getPendingLabTest,
  getRapidAntigenTests,
  // getMolecularLabTests,
  getCueLabTests,
  getAcculaLabTests,
  updateSelectedSite,
  updatePrinter,
  updateEventData,
  deleteTest,
  updateClients,
  updateSites,
  updateLabs,
  updateTestSettings,
  updateTestConfig,
  updateCreateSource,
  updateTestType,
  sendTestToLab,
  updateTestLabType,
  updateTestEmpInfo,
  printerRequest,
  printerRequestSuccess,
  printerRequestFailure,
  updateUserRequest,
};
