export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const UPDATE_USER_REQUEST = 'UPDATE_USER_REQUEST';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_FAILURE = 'UPDATE_USER_FAILURE';

export const GET_LAB_TEST_REQUEST = 'GET_LAB_TEST_REQUEST';
export const GET_LAB_TEST_SUCCESS = 'GET_LAB_TEST_SUCCESS';
export const GET_LAB_TEST_FAILURE = 'GET_LAB_TEST_FAILURE';

export const SEND_TEST_TO_LAB_REQUEST = 'SEND_TEST_TO_LAB_REQUEST';
export const SEND_TEST_TO_LAB_SUCCESS = 'SEND_TEST_TO_LAB_SUCCESS';
export const SEND_TEST_TO_LAB_FAILURE = 'SEND_TEST_TO_LAB_FAILURE';

export const GET_ACCULA_TEST_REQUEST = 'GET_ACCULA_TEST_REQUEST';
export const GET_ACCULA_TEST_SUCCESS = 'GET_ACCULA_TEST_SUCCESS';
export const GET_ACCULA_TEST_FAILURE = 'GET_ACCULA_TEST_FAILURE';

export const GET_CUE_TEST_REQUEST = 'GET_CUE_TEST_REQUEST';
export const GET_CUE_TEST_SUCCESS = 'GET_CUE_TEST_SUCCESS';
export const GET_CUE_TEST_FAILURE = 'GET_CUE_TEST_FAILURE';

export const GET_RAPID_ANTIGEN_TEST_REQUEST = 'GET_RAPID_ANTIGEN_TEST_REQUEST';
export const GET_RAPID_ANTIGEN_TEST_SUCCESS = 'GET_RAPID_ANTIGEN_TEST_SUCCESS';
export const GET_RAPID_ANTIGEN_TEST_FAILURE = 'GET_RAPID_ANTIGEN_TEST_FAILURE';

export const UPDATE_PRINTER = 'UPDATE_PRINTER';

export const PRINTER_REQUEST = 'PRINTER_REQUEST';
export const PRINTER_REQUEST_SUCCESS = 'PRINTER_REQUEST_SUCCESS';
export const PRINTER_REQUEST_FAILURE = 'PRINTER_REQUEST_FAILURE';

export const UPDATE_EVENT_DATA = 'UPDATE_EVENT_DATA';
export const UPDATE_PRINTER_DATA = 'UPDATE_PRINTER_DATA';

export const UPDATE_SELECTED_SITE = 'UPDATE_SELECTED_SITE';

export const SAVE_EMPLOYEE_INFO = 'SAVE_EMPLOYEE_INFO';

export const DELETE_TEST_REQUEST = 'DELETE_TEST_REQUEST';
export const DELETE_TEST_SUCCESS = 'DELETE_TEST_SUCCESS';
export const DELETE_TEST_FAILURE = 'DELETE_TEST_FAILURE';

export const UPDATE_TEST_CONFIG_REQUEST = 'UPDATE_TEST_CONFIG_REQUEST';
export const UPDATE_TEST_CONFIG_SUCCESS = 'UPDATE_TEST_CONFIG_SUCCESS';
export const UPDATE_TEST_CONFIG_FAILURE = 'UPDATE_TEST_CONFIG_FAILURE';

export const UPDATE_TEST_TYPE_REQUEST = 'UPDATE_TEST_TYPE_REQUEST';
export const UPDATE_TEST_TYPE_SUCCESS = 'UPDATE_TEST_TYPE_SUCCESS';
export const UPDATE_TEST_TYPE_FAILURE = 'UPDATE_TEST_TYPE_FAILURE';

export const UPDATE_TEST_EMP_INFO_REQUEST = 'UPDATE_TEST_EMP_INFO_REQUEST';
export const UPDATE_TEST_EMP_INFO_SUCCESS = 'UPDATE_TEST_EMP_INFO_SUCCESS';
export const UPDATE_TEST_EMP_INFO_FAILURE = 'UPDATE_TEST_EMP_INFO_FAILURE';

export const GET_CLIENTS_REQUEST = 'GET_CLIENTS_REQUEST';
export const GET_CLIENTS_SUCCESS = 'GET_CLIENTS_SUCCESS';
export const GET_CLIENTS_FAILURE = 'GET_CLIENTS_FAILURE';

export const UPDATE_CLIENT_LIST = 'UPDATE_CLIENT_LIST';
export const UPDATE_SITE_LIST = 'UPDATE_SITE_LIST';
export const UPDATE_LAB_LIST = 'UPDATE_LAB_LIST';

export const UPDATE_EMPLOYEE_TEST_COUNT = 'UPDATE_EMPLOYEE_TEST_COUNT';

export const UPDATE_TEST_SETTINGS = 'UPDATE_TEST_SETTINGS';

export const CREATE_SOURCE = 'CREATE_SOURCE';

export const UPDATE_TEST_TYPE = 'UPDATE_TEST_TYPE';
