export const Strings = {
  createNew: 'Create New',
  pleaseEnterPhoneNumber: "Please enter a valid phone number.",
  patternConsent: 'Pattern Data Collection\nConsent',
  invalidLicense: 'License # or SSN should have at least 5 characters',
  inValidEmailAddress: 'Invalid email address',
  invalidFirstName: 'Invalid first name',
  invalidLastName: 'Invalid last name',
  invalidAddress: 'Invalid address',
  invalidCity: 'Invalid city',
  invalidState: 'Invalid state',
  invalidZip: 'Invalid zip code',
  invalidPhoneNumber: 'Invalid phone number',
  dobCannotBeFutureData: 'DOB cannot be a future date',
  invalidInsuranceName: 'Invalid insurance name',
  invalidInsuranceNumber: 'Invalid insurance #',
  scanPassport: 'Scan Passport',
  appName: 'SafeCamp',
  firstName: 'First Name',
  authNavigator: 'AuthNavigator',
  mainNavigator: 'MainNavigator',
  login: 'Login',
  signUp: 'SignUp',
  reset: 'Reset',
  confirmCode: 'ConfirmCode',
  home: 'Home',
  startTest: 'StartTest',
  lastName: 'Last Name',
  phonePH: 'Phone Number (888) 888-8888',
  phonePH_1: '(222) 222-2222',
  email: 'Email',
  emailAddress: 'Email Address',
  passwordPH: 'Password (at least 8 characters)',
  create: 'Create',
  signUpTermsOfUse: 'By pressing "Create" below, you agree to the ',
  // TERMS_CONDITION: `By Clicking on Sign In, you are agree to the ${Urls.TERMS_CONDITION_URL} and ${Urls.PRIVACY_POLICY_URL}`,
  termsOfUse: 'Terms of Use',
  privacyPolicy: 'Privacy Policy',
  eventConfiguration: 'Event Configuration',
  testSelection: 'Test Selection Menu',
  pleaseSelectThe: 'Please select the type of test you will be performing',
  startTimer: 'Start timer',
  positive: 'Positive',
  pending: 'Pending',
  pass: 'Pass',
  fail: 'Fail',
  negative: 'Negative',
  location: 'location',
  confirmation: 'Confirmation',
  confirm: 'Confirm',
  deleteMessage: 'Are you sure you want to delete this test?',
  fillConfiguratoin: 'Please configure the event first',
  resendEmailConfirmation: 'Would you like to resend result pdf on updated email address?',
  tubeAlreadyScaned:
    'This scan tube has already been scanned please scan another one.',
  labId: '5e1a1570-c167-40a0-8daa-efe6d3ccdb22',
  newAccount: 'New Account',
  signIn: 'Sign In',
  _signUp: 'Sign Up',
  dont_have_account: "Don't have an account?",
  forgotPassword: 'Forgot Password?',
  resetPass: 'Reset Password',
  sendCode: 'Send Code',
  resendCode: 'Resend Code',
  enterTheConfirmationCode:
    'Enter the confirmation code sent to your phone number',
  discoverPrinter: 'Discover Printer',
  next: 'NEXT',
  update: 'Update',
  pattern: 'Pattern',
  startTesting: 'Start Testing',
  skip: 'Skip',
  password: 'Password',
  inValidEmail: 'Invalid Email!',
  inValidPassword:
    'Password at least 8 characters, 1 num, 1 UC, 1 LC, and 1 SC',
  confirmPhone: 'CONFIRM PHONE',
  userNotFound: 'User not found',
  passwordResetProcessed:
    'Your Password reset has been processed. Please check your phone for the verification code.',
  inValidNewPassword:
    'New password must be at least 8 characters, 1 numeric, 1 uppercase, 1 lowercase, and 1 special character',
  changePassword: 'Change Password',
  newPassword: 'New Password (at least 8 characters)',
  verificationCode: 'Verification Code',
  inValidCode: 'Invalid confirmation code',
  tooManyAttempts: 'Too many attempts. Try again later.',
  someThingWrong: 'Something went wrong. Please try again.',
  sigUpSuccess:
    'Thank you! You have successfully created a SafeCamp MD Account.',
  employeeInfo: 'Employee Info',
  streetAddress: 'Street Address',
  city: 'City',
  statePH: 'State Abbr. XX',
  zipCodePH: 'Zip Code XXXXX-XXXX',
  dobPH: 'DOB MM-DD-YYYY',
  dob: 'DOB',
  licensePH: 'License # or SSN',
  sex: 'Gender',
  gender: 'Gender',
  employeeType: 'Employee Type',
  insuranceName: 'Insurance Name',
  insuranceID: 'Insurance ID#',
  areYouVaccinated: 'Are you Vaccinated?',
  isLucira: 'Lucira Test?',
  whiteGlove: 'White Glove Test?',
  testerDesignation: 'Tester Designation',
  testMenuSelection: 'Test Selection Menu',
  search: 'Search',
  cueTest: 'Cue Tests',
  acculaTest: 'Accula Tests',
  antigenTest: 'Rapid Antigen Tests',
  rapidAntigenTest: 'Rapid Antigen Test List',
  cueTestList: 'Cue Test List',
  acculaTestList: 'Accula Test List',
  labTest: 'Lab Tests',
  labTestList: 'Lab Test List',
  logOut: 'Logout',
  hippaConsent: 'Hippa Consent',
  scanIdQr: 'Scan ID/QR Code',
  scanTestTube: 'Scan Test Tube',
  MYQRCARD: 'MY QR CARD',
  UT: 'UT',
  UserTester: 'User Tester',
  WhatismyQRCodefor: 'What is my QR Code for?',
  Addto: 'Add to',
  AppleWallet: 'Apple Wallet',
  MyQRCODE: 'My QR CODE',
  MyResult: 'My Result',
  selectedPrinter: 'selectedPrinter',
  auth: 'auth',
  datastore: 'datastore',
  ready: 'ready',
  loading: 'Loading',
  drawerNavigator: 'DrawerNavigator',
  lastSessionTime: 'lastSessionTime',
  alert: 'Alert',
  logOutConfirmation: 'Are you sure you want to logout?',
  testAlreadyExist:
    'test is already created for this employee. Do you want to create a new test?',
  patternTestAlert: 'Do you want to also create a Pattern Test?',
  createNewOrUpdate: `doesn't match our current record would you like to update the current record or create a new one?`,
  cancel: 'Cancel',
  yes: 'Yes',
  no: 'No',
  printerConnectSuccess: 'Success Connected to Printer',
  selectPrinter: 'You cannot create a test or print labels. Please edit configuration settings to proceed',
  useBluetooth: `"SafeCamp MD" would like to use bluetooth for new connectionns`,
  allowBlueToothInSettings: 'You can allow new connections in Settings.',
  settings: 'Settings',
  Close: 'Close',
  bluetoothNotAvailable: 'Bluetooth Not Available!',
  printerList: 'List of printers fetched!',
  eventConfigData: 'eventConfigData',
  EditConfiguration: 'Edit Configuration',
  editConfig: 'Edit Config',
  phone: 'Phone',
  addNew: 'Add New',
  noRecord: 'No record found!',
  recordFound: "We found similar records based upon the data entered, Please choose one and proceed.",
  recordFoundLicense: "We found multiple records assign to this license number please choose the appropriate record.",
  PreviousResults: 'Previous Tests',
  CONFIRMATION: 'Confirmation',
  DELETE_MESSAGE: 'Are you sure you want to delete this test',
  staff: 'Staff',
  guest: 'Guest',
  Done: 'Done',
  Date: 'DATE',
  Show: 'SHOW',
  TESTTYPE: 'TEST TYPE',
  RESULTS: 'RESULTS',
  Pleaseselectdate: 'Please select date',
  Pleaseselectshow: 'Please select show',
  Pleaseselecttesttype: 'Please select test type',
  Pleaseselectresult: 'Please select result',
  POSITIVE_RESULT_MESSAGE_START: 'Please confirm you are resulting test ',
  POSITIVE_RESULT_MESSAGE_BULK: 'Please confirm you are resulting ',
  POSITIVE_RESULT_MESSAGE_END: ' to Positive',
  POSITIVE: 'Positive',
  PENDING: 'Pending',
  manual: 'manual',
  SCAN_QR_CODE: 'scan_qr_code',
  SCAN_HR_QR_CODE: 'scan_hr_qr_code',
  SCAN_LICENCE: 'scan_licence',
  SCAN_PRE_REGISTERD: 'scan_pre_registered',
  started: 'started',
  pcr: 'PCR',
  antigen: 'Antigen',
  molecular: 'Molecular',
  other: 'Other',
  TUBE_ALREADY_SCANNED:
    'This scan tube has already been scanned please scan another one.',
  noBarCodeAvailable:
    'No available barcode in this lab. Please select any other lab or wait for some time.',
  sendToLab: 'SEND TO LAB',
  editType: 'Edit Type',
  editResult: 'Edit Result',
  testTypeSelection: 'Test Type Selection',
  testResultSelection: 'Test Result Selection',
  eventConfigSaved:
    'Event Configuration data is saved. Please select a printer to proceed!',
  selectPrinterMessage: 'You cannot create a test or print labels. Please edit configuration settings to proceed',
  selectPrinterToPrintLabel: 'You cannot create a test or print labels. Please edit configuration settings to proceed',
  clear: 'Clear',
  typeUpdatedMsg: 'Test has been updated successfully',
  NoCameraAccess: 'No access to camera',
  typeUpdatedMsgForBul: 'Tests have been updated successfully',
  noScannedTests: 'No Scanned Tests',
  pleaseSelectEventConfig: 'Please select event configuration',
  View: 'View',
  resendCodeSuccess: 'We have successfully sent another code to your phone',
  Filters: 'Filters',
  configrationRemaingAlert:
    'With this configuration, you can not conduct testing or print labels. Are you sure you want to proceed?',
};
export const ScreensName = {
  EVENT: 'event',
  ANTIGEN: 'antigen',
  CUE: 'cue',
  ACCULA: 'accula',
  LAB: 'lab',
};
export const PREFERRENCE_KEYS = {
  LOGIN_DATE: 'login_date'
}
export const SCAN_TYPES = {
  LOOK_UP: 'Lookup',
  SCAN: 'Scan'
}
export const DATE_FORMATES = {
  FORMATTES: [
    'MM-DD-YYYY',
    'DD-MM-YYYY',
    'YYYY-MM-DD',
    'YYYY-DD-MM',
    'DD-YYYY-MM',
    'MM-YYYY-DD',

    'MM/DD/YYYY',
    'DD/MM/YYYY',
    'YYYY/MM/DD',
    'YYYY/DD/MM',
    'DD/YYYY/MM',
    'MM/YYYY/DD',

    'MM DD YYYY',
    'DD MM YYYY',
    'YYYY MM DD',
    'YYYY DD MM',
    'DD YYYY MM',
    'MM YYYY DD',

    'MMDDYYYY',
    'DDMMYYYY',
    'YYYYMMDD',
    'YYYYDDMM',
    'DDYYYYMM',
    'MMYYYYDD',
  ]
}

export default Strings;
